#!/bin/bash
#
# Configure environment for paludis

CHOST="x86_64-pc-linux-gnu"
CFLAGS="${CFLAGS} -march=amdfam10 -minline-stringops-dynamically -O2 -pipe\
    -ftree-vectorize -falign-jumps=64 -fomit-frame-pointer"

CXXFLAGS="${CFLAGS}"
LDFLAGS="${LDFLAGS} -Wl,-O1 -Wl,--hash-style=gnu"
MAKEOPTS="-j8"

#CCACHE_SIZE="4G"
# CCACHE_DIR="/storage/tmp/ccache"
#PATH="/usr/lib/ccache/bin/:${PATH}"
#SANDBOX_WRITE="${SANDBOX_WRITE}:${CCACHE_DIR}"
SKIP_FUNCTIONS=
